# Site settings
author: âœ¨Enigmaâœ¨ (Tammy Leonard-Bruton)
title: âœ¨EnigmasCodingZoneâœ¨
header-img: img/home-bg.png
email: enigmalb@outlook.com
copyright_name: âœ¨Enigmaâœ¨ (Tammy Leonard-Bruton)
description: > # this means to ignore newlines until "baseurl:"
  ğŸ’TheAdventureBeginsğŸ’
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: LeonardBruton
github_username:  LEONARDBRUTON

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
